### ISSUE TITLE
errcode 10006

### ISSUE THREAD

**Issue by emadbrasil** [hadialaddin/bybit-risk-monitor#31]
i'm trying to run this code but i not working

**Comment by hadialaddin** [comment]
Please upload screenshots? Are you sure of your installation steps as explained in the instructions and the video?
Are you sure of your ByBit API Credentials and that you are using the right network (Mainnet or Testnet)?

**Comment by emadbrasil** [comment]
hello,

please check the attachments, i've uploaded a PDF file contains the
screenshots,

really thank you for your help and i appreciate that you are helping me.

the code in my macbook didn't work, then i tried to run the code on my wife
laptop because it's work on windows OS, and still having the problem which
decleared in the screenshots.

i would appreciate it if you have time, i can give you an access to my
computer and help me to make the code run.

thank you again, as i told you " your code is like a life saver for me "

**Comment by hadialaddin** [comment]
@emadbrasil No problem. I can't see the file here, can you upload it somewhere and send the link to download?

**Comment by emadbrasil** [comment]
i solved the problem, the script run very well on my smart phone, thank you
very much.
the problem was that my laptop does not recognize the pybit package, and
the second problem was due to bad internet connection. really thank you for
sharing this code, it's very helpful, and thank you for your awesome support

**Comment by hadialaddin** [comment]
Glad it worked :) good luck!
