### ISSUE TITLE
Version of dependencies(PyBit)

### ISSUE THREAD

**Issue by Pusherman2** [hadialaddin/bybit-risk-monitor#40]
Hi there, I am encountering some errors on execution, specifically related to dependencies from Python.

E.g.: ImportError: cannot import name 'WebSocket' from 'pybit'

Tried different versions of Pybit but either Websocket or "HTTP" modules from Pybit are then missing depending on the version.

Could you be so kind and export your environment/requirements.txt with the correct versions for each dependency?

Thank you and kind regards,

**Comment by hadialaddin** [comment]
Wil try to Dockerize it as a container, to make life easier for deployment.

**Comment by hadialaddin** [comment]
Done, give it a try? Pull and run

pip install -r requirements.txt

**Comment by Pusherman2** [comment]
Hi there, works perfectly, thank you, was indeed specific version required (Tried 2.0.0 and above) but 1.3.2 is required.

As a side question, I setup MSSQL DB using schema provided. Ran the bot but I couldn't get a web/dashboard interface up, how do you access web GUI/Dash, is it local access?

Also is the Auto Trader (Entries) implemented and if so, how would I go about setting that for multiple pairs, I would assume I would need a config per pair and run those in the background using pm2?

Cheers!

**Comment by hadialaddin** [comment]
For Web Dashboard, it is PHP with mySQL, so make sure PHP is running on your server. The Dashboard is at "/dashboard/index.php" wherever your root director is for the crypto-genie.

For the Auto Trader, it will require strong Python knowledge as it is currently implemented in the backend without the frontend. In the config.yaml file you will notice flags 'enforce_tp_dynamic' and 'tp_dynamic' (which already has a few assets added). Just add more assets there and re-run the Python script, no need for multiple instances for each asset. It should monitor them all and execute.

**Comment by Pusherman2** [comment]
Alright that makes sense and I will have a look at the underlying logic there to understand how it works.

Thanks for the additions and clarifications!

Closing this issue.
